import type { TimelineItem } from '~/types/content.types'

export const EXPERIENCE_TIMELINE: TimelineItem[] = [
  {
    id: 'gingerminds',
    periodKey: 'experienceSection.items.gingerminds.period',
    titleKey: 'experienceSection.items.gingerminds.title',
    organizationKey: 'experienceSection.items.gingerminds.organization',
    organizationUrl: 'https://www.gingerminds.fr/?source=maximejolivet.fr',
    logo: '/logo-gingerminds.svg',
    locationKey: 'experienceSection.items.gingerminds.location',
    introKey: 'experienceSection.items.gingerminds.intro',
    descriptionPointsKeys: [
      'experienceSection.items.gingerminds.points.0',
      'experienceSection.items.gingerminds.points.1',
      'experienceSection.items.gingerminds.points.2',
      'experienceSection.items.gingerminds.points.3',
      'experienceSection.items.gingerminds.points.4',
      'experienceSection.items.gingerminds.points.5',
      'experienceSection.items.gingerminds.points.6',
      'experienceSection.items.gingerminds.points.7',
    ],
  },
  {
    id: 'donJigiFest',
    periodKey: 'experienceSection.items.donJigiFest.period',
    titleKey: 'experienceSection.items.donJigiFest.title',
    organizationKey: 'experienceSection.items.donJigiFest.organization',
    organizationUrl: 'https://www.donjigifest.org/',
    locationKey: 'experienceSection.items.donJigiFest.location',
    descriptionKey: 'experienceSection.items.donJigiFest.description',
  },
  {
    id: 'greentech',
    periodKey: 'experienceSection.items.greentech.period',
    titleKey: 'experienceSection.items.greentech.title',
    organizationKey: 'experienceSection.items.greentech.organization',
    organizationUrl: 'https://greentech.sn/',
    locationKey: 'experienceSection.items.greentech.location',
    descriptionKey: 'experienceSection.items.greentech.description',
  },
  {
    id: 'laSalleSaintJoseph',
    periodKey: 'experienceSection.items.laSalleSaintJoseph.period',
    titleKey: 'experienceSection.items.laSalleSaintJoseph.title',
    organizationKey: 'experienceSection.items.laSalleSaintJoseph.organization',
    organizationUrl: 'https://www.lasalle-stjoseph-argentre.org/',
    locationKey: 'experienceSection.items.laSalleSaintJoseph.location',
    descriptionKey: 'experienceSection.items.laSalleSaintJoseph.description',
  },
  {
    id: 'chSimoneVeil',
    periodKey: 'experienceSection.items.chSimoneVeil.period',
    titleKey: 'experienceSection.items.chSimoneVeil.title',
    organizationKey: 'experienceSection.items.chSimoneVeil.organization',
    organizationUrl: 'https://www.ch-vitre.fr/',
    locationKey: 'experienceSection.items.chSimoneVeil.location',
    descriptionKey: 'experienceSection.items.chSimoneVeil.description',
  },
]
