export interface CaseStudy {
  id: string
  slug: string
  year: string
  dot: 'mint' | 'gold'
  live: boolean
  category: 'pro' | 'personal'
  company?: string
  employer?: string
  websiteUrl?: string
  image?: string
  tags: string[]
  typeKey: string
  titleKey: string
  taglineKey: string
  impactKey: string
  contexteKey: string
  solutionKey: string
  pointsKeys: string[]
  resultatKey: string
  roleKey: string
  dureeKey: string
  equipeKey: string
}

export const CASE_STUDIES: CaseStudy[] = [
  {
    id: 'saur',
    slug: 'saur',
    year: '2025',
    dot: 'mint',
    live: false,
    category: 'pro',
    company: 'Saur',
    websiteUrl: 'https://www.saur.com',
    employer: 'Gingerminds',
    tags: ['WordPress'],
    typeKey: 'projects.saur.type',
    titleKey: 'projects.saur.title',
    taglineKey: 'projects.saur.tagline',
    impactKey: 'projects.saur.impact',
    contexteKey: 'projects.saur.contexte',
    solutionKey: 'projects.saur.solution',
    pointsKeys: [
      'projects.saur.points.0',
      'projects.saur.points.1',
      'projects.saur.points.2',
      'projects.saur.points.3',
    ],
    resultatKey: 'projects.saur.resultat',
    roleKey: 'projects.saur.role',
    dureeKey: 'projects.saur.duree',
    equipeKey: 'projects.saur.equipe',
  },
  {
    id: 'vygon',
    slug: 'vygon',
    year: '2024',
    dot: 'mint',
    live: true,
    category: 'pro',
    company: 'Vygon',
    websiteUrl: 'https://www.vygon.com',
    employer: 'Gingerminds',
    image: '/projects/vygon.jpg',
    tags: [
      'Drupal 10',
      'Multilingue',
      'Multi-site',
      'Catalogue produits',
      'Site corporate',
      'Site de marque',
    ],
    typeKey: 'projects.vygon.type',
    titleKey: 'projects.vygon.title',
    taglineKey: 'projects.vygon.tagline',
    impactKey: 'projects.vygon.impact',
    contexteKey: 'projects.vygon.contexte',
    solutionKey: 'projects.vygon.solution',
    pointsKeys: [
      'projects.vygon.points.0',
      'projects.vygon.points.1',
      'projects.vygon.points.2',
      'projects.vygon.points.3',
    ],
    resultatKey: 'projects.vygon.resultat',
    roleKey: 'projects.vygon.role',
    dureeKey: 'projects.vygon.duree',
    equipeKey: 'projects.vygon.equipe',
  },
  {
    id: 'pileje',
    slug: 'pileje',
    year: '2019',
    dot: 'gold',
    live: false,
    category: 'pro',
    company: 'PiLeJe',
    websiteUrl: 'https://www.pileje.fr',
    employer: 'Gingerminds',
    tags: ['Drupal 10', 'Multilingue', 'Multi-site', 'Site corporate', 'Site de marque'],
    typeKey: 'projects.pileje.type',
    titleKey: 'projects.pileje.title',
    taglineKey: 'projects.pileje.tagline',
    impactKey: 'projects.pileje.impact',
    contexteKey: 'projects.pileje.contexte',
    solutionKey: 'projects.pileje.solution',
    pointsKeys: [
      'projects.pileje.points.0',
      'projects.pileje.points.1',
      'projects.pileje.points.2',
      'projects.pileje.points.3',
    ],
    resultatKey: 'projects.pileje.resultat',
    roleKey: 'projects.pileje.role',
    dureeKey: 'projects.pileje.duree',
    equipeKey: 'projects.pileje.equipe',
  },
  {
    id: 'boralex',
    slug: 'boralex',
    year: '2024',
    dot: 'mint',
    live: true,
    category: 'pro',
    company: 'Boralex',
    websiteUrl: 'https://www.boralex.com',
    employer: 'Gingerminds',
    tags: ['Drupal 10', 'Site institutionnel'],
    typeKey: 'projects.boralex.type',
    titleKey: 'projects.boralex.title',
    taglineKey: 'projects.boralex.tagline',
    impactKey: 'projects.boralex.impact',
    contexteKey: 'projects.boralex.contexte',
    solutionKey: 'projects.boralex.solution',
    pointsKeys: [
      'projects.boralex.points.0',
      'projects.boralex.points.1',
      'projects.boralex.points.2',
      'projects.boralex.points.3',
    ],
    resultatKey: 'projects.boralex.resultat',
    roleKey: 'projects.boralex.role',
    dureeKey: 'projects.boralex.duree',
    equipeKey: 'projects.boralex.equipe',
  },
  {
    id: 'groupe-techna',
    slug: 'groupe-techna',
    year: '2021',
    dot: 'gold',
    live: true,
    category: 'pro',
    company: 'Groupe Techna',
    websiteUrl: 'https://www.groupe-techna.com',
    employer: 'Gingerminds',
    tags: ['Drupal 10', 'Multi-site', 'Multilingue', 'Site corporate'],
    typeKey: 'projects.groupeTechna.type',
    titleKey: 'projects.groupeTechna.title',
    taglineKey: 'projects.groupeTechna.tagline',
    impactKey: 'projects.groupeTechna.impact',
    contexteKey: 'projects.groupeTechna.contexte',
    solutionKey: 'projects.groupeTechna.solution',
    pointsKeys: [
      'projects.groupeTechna.points.0',
      'projects.groupeTechna.points.1',
      'projects.groupeTechna.points.2',
      'projects.groupeTechna.points.3',
    ],
    resultatKey: 'projects.groupeTechna.resultat',
    roleKey: 'projects.groupeTechna.role',
    dureeKey: 'projects.groupeTechna.duree',
    equipeKey: 'projects.groupeTechna.equipe',
  },
  {
    id: 'chtiiing',
    slug: 'chtiiing',
    year: '2022',
    dot: 'mint',
    live: true,
    category: 'pro',
    company: 'Chtiiing',
    websiteUrl: 'https://chtiiing-nantes.fr',
    employer: 'Gingerminds',
    tags: ['WordPress', 'Site vitrine'],
    typeKey: 'projects.chtiiing.type',
    titleKey: 'projects.chtiiing.title',
    taglineKey: 'projects.chtiiing.tagline',
    impactKey: 'projects.chtiiing.impact',
    contexteKey: 'projects.chtiiing.contexte',
    solutionKey: 'projects.chtiiing.solution',
    pointsKeys: [
      'projects.chtiiing.points.0',
      'projects.chtiiing.points.1',
      'projects.chtiiing.points.2',
      'projects.chtiiing.points.3',
    ],
    resultatKey: 'projects.chtiiing.resultat',
    roleKey: 'projects.chtiiing.role',
    dureeKey: 'projects.chtiiing.duree',
    equipeKey: 'projects.chtiiing.equipe',
  },
  {
    id: 'lna-sante',
    slug: 'lna-sante',
    year: '2021',
    dot: 'gold',
    live: true,
    category: 'pro',
    company: 'LNA Santé',
    websiteUrl: 'https://www.lna-sante.com',
    employer: 'Gingerminds',
    tags: ['WordPress', 'Multi-site', 'Site corporate'],
    typeKey: 'projects.lnaSante.type',
    titleKey: 'projects.lnaSante.title',
    taglineKey: 'projects.lnaSante.tagline',
    impactKey: 'projects.lnaSante.impact',
    contexteKey: 'projects.lnaSante.contexte',
    solutionKey: 'projects.lnaSante.solution',
    pointsKeys: [
      'projects.lnaSante.points.0',
      'projects.lnaSante.points.1',
      'projects.lnaSante.points.2',
      'projects.lnaSante.points.3',
    ],
    resultatKey: 'projects.lnaSante.resultat',
    roleKey: 'projects.lnaSante.role',
    dureeKey: 'projects.lnaSante.duree',
    equipeKey: 'projects.lnaSante.equipe',
  },
  {
    id: 'onet-business',
    slug: 'onet-business',
    year: '2021',
    dot: 'mint',
    live: true,
    category: 'pro',
    company: 'Onet Business Services',
    websiteUrl: 'https://www.onet.fr/',
    employer: 'Gingerminds',
    tags: ['WordPress', 'Elementor', 'Site institutionnel'],
    typeKey: 'projects.onetBusiness.type',
    titleKey: 'projects.onetBusiness.title',
    taglineKey: 'projects.onetBusiness.tagline',
    impactKey: 'projects.onetBusiness.impact',
    contexteKey: 'projects.onetBusiness.contexte',
    solutionKey: 'projects.onetBusiness.solution',
    pointsKeys: [
      'projects.onetBusiness.points.0',
      'projects.onetBusiness.points.1',
      'projects.onetBusiness.points.2',
      'projects.onetBusiness.points.3',
    ],
    resultatKey: 'projects.onetBusiness.resultat',
    roleKey: 'projects.onetBusiness.role',
    dureeKey: 'projects.onetBusiness.duree',
    equipeKey: 'projects.onetBusiness.equipe',
  },
  {
    id: 'precia-molen',
    slug: 'precia-molen',
    year: '2026',
    dot: 'gold',
    live: true,
    category: 'pro',
    company: 'Precia Molen',
    websiteUrl: 'https://www.preciamolen.com',
    employer: 'Gingerminds',
    tags: ['Drupal 11', 'Site institutionnel'],
    typeKey: 'projects.preciaMolen.type',
    titleKey: 'projects.preciaMolen.title',
    taglineKey: 'projects.preciaMolen.tagline',
    impactKey: 'projects.preciaMolen.impact',
    contexteKey: 'projects.preciaMolen.contexte',
    solutionKey: 'projects.preciaMolen.solution',
    pointsKeys: [
      'projects.preciaMolen.points.0',
      'projects.preciaMolen.points.1',
      'projects.preciaMolen.points.2',
      'projects.preciaMolen.points.3',
    ],
    resultatKey: 'projects.preciaMolen.resultat',
    roleKey: 'projects.preciaMolen.role',
    dureeKey: 'projects.preciaMolen.duree',
    equipeKey: 'projects.preciaMolen.equipe',
  },
  {
    id: 'akena',
    slug: 'akena',
    year: '2023',
    dot: 'mint',
    live: true,
    category: 'pro',
    company: 'Akena',
    websiteUrl: 'https://www.akena.com',
    employer: 'Gingerminds',
    tags: ['Typo3 - Drupal 8 9 10', 'Multi-site', 'Site produit et de marque'],
    typeKey: 'projects.akena.type',
    titleKey: 'projects.akena.title',
    taglineKey: 'projects.akena.tagline',
    impactKey: 'projects.akena.impact',
    contexteKey: 'projects.akena.contexte',
    solutionKey: 'projects.akena.solution',
    pointsKeys: [
      'projects.akena.points.0',
      'projects.akena.points.1',
      'projects.akena.points.2',
      'projects.akena.points.3',
    ],
    resultatKey: 'projects.akena.resultat',
    roleKey: 'projects.akena.role',
    dureeKey: 'projects.akena.duree',
    equipeKey: 'projects.akena.equipe',
  },
  {
    id: 'groupe-samse-recrute',
    slug: 'groupe-samse-recrute',
    year: '2021',
    dot: 'gold',
    live: true,
    category: 'pro',
    company: 'Groupe SAMSE Recrute',
    websiteUrl: 'https://www.groupesamserecrute.fr',
    employer: 'Gingerminds',
    tags: ['Drupal 8 9 10', 'Marque employeur'],
    typeKey: 'projects.groupeSamseRecrute.type',
    titleKey: 'projects.groupeSamseRecrute.title',
    taglineKey: 'projects.groupeSamseRecrute.tagline',
    impactKey: 'projects.groupeSamseRecrute.impact',
    contexteKey: 'projects.groupeSamseRecrute.contexte',
    solutionKey: 'projects.groupeSamseRecrute.solution',
    pointsKeys: [
      'projects.groupeSamseRecrute.points.0',
      'projects.groupeSamseRecrute.points.1',
      'projects.groupeSamseRecrute.points.2',
      'projects.groupeSamseRecrute.points.3',
    ],
    resultatKey: 'projects.groupeSamseRecrute.resultat',
    roleKey: 'projects.groupeSamseRecrute.role',
    dureeKey: 'projects.groupeSamseRecrute.duree',
    equipeKey: 'projects.groupeSamseRecrute.equipe',
  },
  {
    id: 'ludmigo',
    slug: 'ludmigo',
    year: '2026',
    dot: 'mint',
    live: true,
    category: 'personal',
    websiteUrl: 'https://github.com/maximejolivet/ludmigo',
    tags: ['Laravel', 'Vue'],
    typeKey: 'projects.ludmigo.type',
    titleKey: 'projects.ludmigo.title',
    taglineKey: 'projects.ludmigo.tagline',
    impactKey: 'projects.ludmigo.impact',
    contexteKey: 'projects.ludmigo.contexte',
    solutionKey: 'projects.ludmigo.solution',
    pointsKeys: [
      'projects.ludmigo.points.0',
      'projects.ludmigo.points.1',
      'projects.ludmigo.points.2',
      'projects.ludmigo.points.3',
    ],
    resultatKey: 'projects.ludmigo.resultat',
    roleKey: 'projects.ludmigo.role',
    dureeKey: 'projects.ludmigo.duree',
    equipeKey: 'projects.ludmigo.equipe',
  },
  {
    id: 'portfolio',
    slug: 'portfolio',
    year: '2026',
    dot: 'mint',
    live: true,
    category: 'personal',
    websiteUrl: 'https://maximejolivet.fr',
    tags: ['Nuxt 4', 'Vue 3', 'Tailwind v4', 'shadcn-vue', 'Supabase', 'i18n'],
    typeKey: 'projects.portfolio.type',
    titleKey: 'projects.portfolio.title',
    taglineKey: 'projects.portfolio.tagline',
    impactKey: 'projects.portfolio.impact',
    contexteKey: 'projects.portfolio.contexte',
    solutionKey: 'projects.portfolio.solution',
    pointsKeys: [
      'projects.portfolio.points.0',
      'projects.portfolio.points.1',
      'projects.portfolio.points.2',
      'projects.portfolio.points.3',
    ],
    resultatKey: 'projects.portfolio.resultat',
    roleKey: 'projects.portfolio.role',
    dureeKey: 'projects.portfolio.duree',
    equipeKey: 'projects.portfolio.equipe',
  },
]
